'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.296
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MiniPDV.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE TABLE IF NOT EXISTS [ajustes] (
        '''    [id] integer PRIMARY KEY NOT NULL,
        '''    [sucursal] integer NOT NULL,
        '''    [producto_id] integer NOT NULL,
        '''    [cantidadvieja] integer NOT NULL,
        '''    [cantidadnueva] integer NOT NULL,
        '''    [usuario_id] integer NOT NULL,
        '''    [fecha] datetime NOT NULL
        ''');
        '''CREATE TABLE IF NOT EXISTS [config] (
        '''    [id] integer PRIMARY KEY NOT NULL,
        '''    [sucursal] integer NOT NULL DEFAULT 0,
        '''    [nombre] varchar(255) NOT NULL DEFAULT &apos;No asignada&apos;
        ''');
        '''CREATE TABLE IF NOT EXISTS [c [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property basededatos() As String
            Get
                Return ResourceManager.GetString("basededatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO &quot;config&quot; VALUES(1,0,&apos;NOMBRE DE LA SUCURSAL&apos;);.
        '''</summary>
        Friend ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO &quot;destinos&quot; VALUES(1,18000,&apos;ALM SP CENT NAYARIT &apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(2,14000,&apos;ALM SP CENT AGUASCAL&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(3,17000,&apos;ALM SP CENT ZACATECA&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(4,18701,&apos;SAN JOSE DEL VALLE&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(5,18702,&apos;ACAPOTENA&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(6,18703,&apos;GENTE DE TEPIC&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(7,18704,&apos;TECUALA&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(8,18705,&apos;VILLA HIDALGO&apos;);
        '''INSERT INTO &quot;destinos&quot; VALUES(9,18706,&apos; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property destinos() As String
            Get
                Return ResourceManager.GetString("destinos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO &quot;productos&quot; VALUES(1,&apos;101&apos;,&apos;7501165005709&apos;,&apos;ACIDO ACETILSALICILICO GI 500 MG 20 TABSX&apos;,10,&apos;2013-03-19 13:42:32&apos;,0);
        '''INSERT INTO &quot;productos&quot; VALUES(2,&apos;103&apos;,&apos;7501125195556&apos;,&apos;ACIDO ACETILSALICILICO 300 MG 20 TABS EFERV&apos;,10,&apos;2013-03-19 13:18:01&apos;,0);
        '''INSERT INTO &quot;productos&quot; VALUES(3,&apos;104&apos;,&apos;7501571200552&apos;,&apos;PARACETAMOL (ACETAMINOFEN) 500 MG 10 TABLETAS&apos;,10,&apos;2013-03-19 13:46:17&apos;,0);
        '''INSERT INTO &quot;productos&quot; VALUES(4,&apos;105&apos;,&apos;7502226290188&apos;,&apos;PARACETAMOL (ACETAMINOFEN) 300 MG SUPOSITORIOS&apos;,10,&apos;2013-03-19  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property productos() As String
            Get
                Return ResourceManager.GetString("productos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO &quot;ticket&quot; VALUES(&apos;FVA961108MD7&apos;,&apos;FARMACIAS DE VANGUARDIA SA DE CV&apos;,&apos;LAGO TRASIMENO 36 COLONIA ANAHUAC C P 11320&apos;,&apos;MEXICO D F&apos;,&apos;&apos;,&apos;&apos;,&apos;&apos;,&apos;&apos;,1);.
        '''</summary>
        Friend ReadOnly Property ticket() As String
            Get
                Return ResourceManager.GetString("ticket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO &quot;tipo_salida&quot; VALUES(1,1,&apos;Caducados&apos;);
        '''INSERT INTO &quot;tipo_salida&quot; VALUES(2,2,&apos;Maltratados&apos;);
        '''INSERT INTO &quot;tipo_salida&quot; VALUES(3,3,&apos;Proximos a caducar&apos;);
        '''INSERT INTO &quot;tipo_salida&quot; VALUES(4,4,&apos;Transpaso&apos;);
        '''INSERT INTO &quot;tipo_salida&quot; VALUES(5,5,&apos;Devolución po excedente&apos;);.
        '''</summary>
        Friend ReadOnly Property tipo_salida() As String
            Get
                Return ResourceManager.GetString("tipo_salida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO &quot;usuarios&quot; VALUES(1,&apos;admin&apos;,&apos;f3n1x&apos;,&apos;Administrador del sistema&apos;,1,12345,1);.
        '''</summary>
        Friend ReadOnly Property usuarios() As String
            Get
                Return ResourceManager.GetString("usuarios", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
