'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.296
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.296.
'
Namespace Fargente
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="genteBinding", [Namespace]:="urn:gente")>  _
    Partial Public Class gente
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private productosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private sucursalesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private tiposalidaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private recetaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private corteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private inviniOperationCompleted As System.Threading.SendOrPostCallback
        
        Private entradaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private salidaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ajusteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private missingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MiniPDV.My.MySettings.Default.inventarioFnx_Gente_gente
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event productosCompleted As productosCompletedEventHandler
        
        '''<remarks/>
        Public Event sucursalesCompleted As sucursalesCompletedEventHandler
        
        '''<remarks/>
        Public Event tiposalidaCompleted As tiposalidaCompletedEventHandler
        
        '''<remarks/>
        Public Event recetaCompleted As recetaCompletedEventHandler
        
        '''<remarks/>
        Public Event corteCompleted As corteCompletedEventHandler
        
        '''<remarks/>
        Public Event inviniCompleted As inviniCompletedEventHandler
        
        '''<remarks/>
        Public Event entradaCompleted As entradaCompletedEventHandler
        
        '''<remarks/>
        Public Event salidaCompleted As salidaCompletedEventHandler
        
        '''<remarks/>
        Public Event ajusteCompleted As ajusteCompletedEventHandler
        
        '''<remarks/>
        Public Event missingCompleted As missingCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#productos", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function productos(ByVal mac As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("productos", New Object() {mac})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub productosAsync(ByVal mac As String)
            Me.productosAsync(mac, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub productosAsync(ByVal mac As String, ByVal userState As Object)
            If (Me.productosOperationCompleted Is Nothing) Then
                Me.productosOperationCompleted = AddressOf Me.OnproductosOperationCompleted
            End If
            Me.InvokeAsync("productos", New Object() {mac}, Me.productosOperationCompleted, userState)
        End Sub
        
        Private Sub OnproductosOperationCompleted(ByVal arg As Object)
            If (Not (Me.productosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent productosCompleted(Me, New productosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#sucursales", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function sucursales(ByVal mac As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("sucursales", New Object() {mac})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub sucursalesAsync(ByVal mac As String)
            Me.sucursalesAsync(mac, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub sucursalesAsync(ByVal mac As String, ByVal userState As Object)
            If (Me.sucursalesOperationCompleted Is Nothing) Then
                Me.sucursalesOperationCompleted = AddressOf Me.OnsucursalesOperationCompleted
            End If
            Me.InvokeAsync("sucursales", New Object() {mac}, Me.sucursalesOperationCompleted, userState)
        End Sub
        
        Private Sub OnsucursalesOperationCompleted(ByVal arg As Object)
            If (Not (Me.sucursalesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent sucursalesCompleted(Me, New sucursalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#tiposalida", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function tiposalida(ByVal mac As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("tiposalida", New Object() {mac})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub tiposalidaAsync(ByVal mac As String)
            Me.tiposalidaAsync(mac, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub tiposalidaAsync(ByVal mac As String, ByVal userState As Object)
            If (Me.tiposalidaOperationCompleted Is Nothing) Then
                Me.tiposalidaOperationCompleted = AddressOf Me.OntiposalidaOperationCompleted
            End If
            Me.InvokeAsync("tiposalida", New Object() {mac}, Me.tiposalidaOperationCompleted, userState)
        End Sub
        
        Private Sub OntiposalidaOperationCompleted(ByVal arg As Object)
            If (Not (Me.tiposalidaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent tiposalidaCompleted(Me, New tiposalidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#receta", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function receta(<System.Xml.Serialization.SoapElementAttribute("receta")> ByVal receta1 As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("receta", New Object() {receta1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub recetaAsync(ByVal receta1 As String)
            Me.recetaAsync(receta1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub recetaAsync(ByVal receta1 As String, ByVal userState As Object)
            If (Me.recetaOperationCompleted Is Nothing) Then
                Me.recetaOperationCompleted = AddressOf Me.OnrecetaOperationCompleted
            End If
            Me.InvokeAsync("receta", New Object() {receta1}, Me.recetaOperationCompleted, userState)
        End Sub
        
        Private Sub OnrecetaOperationCompleted(ByVal arg As Object)
            If (Not (Me.recetaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent recetaCompleted(Me, New recetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#corte", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function corte(<System.Xml.Serialization.SoapElementAttribute("corte")> ByVal corte1 As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("corte", New Object() {corte1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub corteAsync(ByVal corte1 As String)
            Me.corteAsync(corte1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub corteAsync(ByVal corte1 As String, ByVal userState As Object)
            If (Me.corteOperationCompleted Is Nothing) Then
                Me.corteOperationCompleted = AddressOf Me.OncorteOperationCompleted
            End If
            Me.InvokeAsync("corte", New Object() {corte1}, Me.corteOperationCompleted, userState)
        End Sub
        
        Private Sub OncorteOperationCompleted(ByVal arg As Object)
            If (Not (Me.corteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent corteCompleted(Me, New corteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#invini", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function invini(<System.Xml.Serialization.SoapElementAttribute("invini")> ByVal invini1 As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("invini", New Object() {invini1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub inviniAsync(ByVal invini1 As String)
            Me.inviniAsync(invini1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub inviniAsync(ByVal invini1 As String, ByVal userState As Object)
            If (Me.inviniOperationCompleted Is Nothing) Then
                Me.inviniOperationCompleted = AddressOf Me.OninviniOperationCompleted
            End If
            Me.InvokeAsync("invini", New Object() {invini1}, Me.inviniOperationCompleted, userState)
        End Sub
        
        Private Sub OninviniOperationCompleted(ByVal arg As Object)
            If (Not (Me.inviniCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent inviniCompleted(Me, New inviniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#entrada", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function entrada(<System.Xml.Serialization.SoapElementAttribute("entrada")> ByVal entrada1 As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("entrada", New Object() {entrada1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub entradaAsync(ByVal entrada1 As String)
            Me.entradaAsync(entrada1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub entradaAsync(ByVal entrada1 As String, ByVal userState As Object)
            If (Me.entradaOperationCompleted Is Nothing) Then
                Me.entradaOperationCompleted = AddressOf Me.OnentradaOperationCompleted
            End If
            Me.InvokeAsync("entrada", New Object() {entrada1}, Me.entradaOperationCompleted, userState)
        End Sub
        
        Private Sub OnentradaOperationCompleted(ByVal arg As Object)
            If (Not (Me.entradaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent entradaCompleted(Me, New entradaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#salida", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function salida(<System.Xml.Serialization.SoapElementAttribute("salida")> ByVal salida1 As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("salida", New Object() {salida1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub salidaAsync(ByVal salida1 As String)
            Me.salidaAsync(salida1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub salidaAsync(ByVal salida1 As String, ByVal userState As Object)
            If (Me.salidaOperationCompleted Is Nothing) Then
                Me.salidaOperationCompleted = AddressOf Me.OnsalidaOperationCompleted
            End If
            Me.InvokeAsync("salida", New Object() {salida1}, Me.salidaOperationCompleted, userState)
        End Sub
        
        Private Sub OnsalidaOperationCompleted(ByVal arg As Object)
            If (Not (Me.salidaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent salidaCompleted(Me, New salidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#ajuste", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function ajuste(<System.Xml.Serialization.SoapElementAttribute("ajuste")> ByVal ajuste1 As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ajuste", New Object() {ajuste1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ajusteAsync(ByVal ajuste1 As String)
            Me.ajusteAsync(ajuste1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ajusteAsync(ByVal ajuste1 As String, ByVal userState As Object)
            If (Me.ajusteOperationCompleted Is Nothing) Then
                Me.ajusteOperationCompleted = AddressOf Me.OnajusteOperationCompleted
            End If
            Me.InvokeAsync("ajuste", New Object() {ajuste1}, Me.ajusteOperationCompleted, userState)
        End Sub
        
        Private Sub OnajusteOperationCompleted(ByVal arg As Object)
            If (Not (Me.ajusteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ajusteCompleted(Me, New ajusteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gente#missing", RequestNamespace:="urn:gente", ResponseNamespace:="urn:gente")>  _
        Public Function missing(ByVal sucursal As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("missing", New Object() {sucursal})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub missingAsync(ByVal sucursal As String)
            Me.missingAsync(sucursal, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub missingAsync(ByVal sucursal As String, ByVal userState As Object)
            If (Me.missingOperationCompleted Is Nothing) Then
                Me.missingOperationCompleted = AddressOf Me.OnmissingOperationCompleted
            End If
            Me.InvokeAsync("missing", New Object() {sucursal}, Me.missingOperationCompleted, userState)
        End Sub
        
        Private Sub OnmissingOperationCompleted(ByVal arg As Object)
            If (Not (Me.missingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent missingCompleted(Me, New missingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub productosCompletedEventHandler(ByVal sender As Object, ByVal e As productosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class productosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub sucursalesCompletedEventHandler(ByVal sender As Object, ByVal e As sucursalesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class sucursalesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub tiposalidaCompletedEventHandler(ByVal sender As Object, ByVal e As tiposalidaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class tiposalidaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub recetaCompletedEventHandler(ByVal sender As Object, ByVal e As recetaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class recetaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub corteCompletedEventHandler(ByVal sender As Object, ByVal e As corteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class corteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub inviniCompletedEventHandler(ByVal sender As Object, ByVal e As inviniCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class inviniCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub entradaCompletedEventHandler(ByVal sender As Object, ByVal e As entradaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class entradaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub salidaCompletedEventHandler(ByVal sender As Object, ByVal e As salidaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class salidaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ajusteCompletedEventHandler(ByVal sender As Object, ByVal e As ajusteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ajusteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub missingCompletedEventHandler(ByVal sender As Object, ByVal e As missingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class missingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
